### ISSUE TITLE
Thanks you so much.

### ISSUE THREAD

**Issue by Jacobw1oo** [MastaG/mesa-turnip-ppa#1]
Thanks, out of curiosity. what is your  version of this command ( all of my drivers are trash)
meson build64/ --prefix /usr --libdir lib/aarch64-linux-gnu/ -D platforms=x11,wayland -D gallium-drivers=freedreno -D vulkan-drivers=freedreno -D freedreno-kmds=msm,kgsl -D dri3=enabled -D buildtype=release

**Comment by MastaG** [comment]
For the Android builds on the releases page its:
```--cross-file "$workdir"/mesa/android-aarch64 -Dbuildtype=release -Dplatforms=android -Dplatform-sdk-version=$sdkver -Dandroid-stub=true -Dgallium-drivers= -Dvulkan-drivers=freedreno -Dvulkan-beta=true -Dfreedreno-kmds=kgsl -Db_lto=true```

For the mesa package in the PPA, it just takes the Debian/Ubuntu defaults and the script will only add: ```-Dfreedreno-kmds=msm,kgsl```
The build log doesn't specify the exact meson command, but it outputs the build flags though.
You can find it here:
https://launchpadlibrarian.net/740714162/buildlog_ubuntu-oracular-amd64.mesa_24.3~git2407230600.74b4c9~oibaf-turnip-kgsl~o_BUILDING.txt.gz
