### ISSUE TITLE
Segmentation Fault issue

### ISSUE THREAD

**Issue by Jacobw1oo** [MastaG/mesa-turnip-ppa#4]
Posted on 2024 09 06 for the  24 09 03 0600 package.
So i did a full system upgrade today (Ubuntu 24.04), and to my displeases xfce4 now had segment faults, Plasma does not work either. 
Using gdb i have isolated the first issue to LibGLX_mesa from libglx-mesa0_24.3~git2409030600.

It has complete broken my system i dont know what to do?

edit:
i tried rolling back to older update (total fail, don't have all packages cache), i am going to start llvm and see if i can run xfce4 (failed, llvm is part of the graphics driver.)
LIBGL_ALWAYS_SOFTWARE=1 taskset -c 4-7 startxfce4 - Segmentation Fault
taskset -c 4-7 startplasma-x11 -  It get into a crash loop, but wont give good details.
All of the sub components for xfce4 that i have tested(10), point to Seg Fault in libGLX_mesa.so.0

Was hoping that updates would fix the issue but build failed,
mesa (24.3 git2409150600.46b561 oibaf-turnip-kgsl~o) oracular/noble
Last 20 (or so) builds have failed.

**Comment by Jacobw1oo** [comment]
I have found a solution.

sudo apt-get download   libglx-mesa0=24.0.9-0ubuntu0.1 libglx-mesa0:armhf=24.0.9-0ubuntu0.1 libglapi-mesa:armhf=24.0.9-0ubuntu0.1 libglapi-mesa=24.0.9-0ubuntu0.1

sudo dpkg -i --force-overwrite ./libglx-mesa0_24.0.9-0ubuntu0.1_arm64.deb ./libglx-mesa0_24.0.9-0ubuntu0.1_armhf.deb  ./libglapi-mesa_24.0.9-0ubuntu0.1_arm64.deb ./libglapi-mesa_24.0.9-0ubuntu0.1_armhf.deb

This fixed my issue but opengl is still broken.

For additional information: apt-cache policy libglx-mesa0 | apt-cache madison libglx-mesa0 
I how i found the version from another repo and found how to select version for download.

**Comment by blazingcody0707** [comment]
Since opengl is broken you're gonna have to build gl4es I tested it with glmark2 and it worked since I built gl4es

**Comment by blazingcody0707** [comment]
![Screenshot_20240927_021649_TermuxX11](https://github.com/user-attachments/assets/c2bbd33a-f54c-4810-9a39-e720aaa87779)

**Comment by Jacobw1oo** [comment]
i will give it a try, but i have a deeper issue the newest packages installed for mesa-turnip-ppa are broken, his night bot has been broken the last month. I had a working set back in 2024 07 but the last package 2024 09 , i have like 40 packages that don't line up now, cant use apt until the repo is fixed.

I compiled and installed gl4es form PitSeb did not fix the issue, going to try to compile libglx and reset all the other packages and align them. My issue is i don't have a good libGLX-mesa0, i think my only option is to compile mesa :( , that never works for me.

**Comment by blazingcody0707** [comment]
You're maybe also have to maybe install these apt update -y && apt upgrade -y
apt install libterm-readline-gnu-perl sudo software-properties-common -y
sudo apt install binfmt-support libsdl2-dev libepoxy-dev libssl-dev nasm squashfs-tools squashfuse python3 -y

**Comment by Jacobw1oo** [comment]
I have fixed it, by doing a full system rebuild with Ubuntu 24.10 Beta instead of Ubuntu 24.04.

**Comment by MastaG** [comment]
The build pipelines are not building for a while now because the dri3.patch needs to be rebased on mesa main git.
It could be that the last working build for 24.04 had a regression.
If you have time feel free to rebase the patch on mesa main git and submit a PR.
I can only do this after 2 weeks when I get back from vacation.

**Comment by Jacobw1oo** [comment]
I will give it a try, I trying to to test, struggling to download my changed dir3-patch.

**Comment by Jacobw1oo** [comment]
Attempted to patch, fixed 13 mismatch issues, there are 2 i tried to fix  but not confident there fully correct (notes in request). It is awaiting your checking and approval to be merged.
